const slider1 = tns({
  container: ".promo__slider",
  items: 5,
  slideBy: "page",
  autoplay: true,
  nav: false,
  seed: 300,
  autoplayTimeout: 0,
  loop: true,
  controlsContainer: false,
  controls: false,
  autoplayButtonOutput: false,
  gutter: 30,
  autoWidth: true,
});

const slider2 = tns({
  container: ".reviews__slider",
  items: 3,
  slideBy: "page",
  autoplay: true,
  nav: false,
  seed: 300,
  autoplayTimeout: 0,
  loop: true,
  controlsContainer: false,
  controls: false,
  autoplayButtonOutput: false,
  autoWidth: true,
  axis: "vertical",
});

const slider3 = tns({
  container: ".reviews__slider_middle",
  items: 3,
  slideBy: "page",
  autoplay: true,
  nav: false,
  seed: 300,
  autoplayTimeout: 0,
  loop: true,
  controlsContainer: false,
  controls: false,
  autoplayButtonOutput: false,
  autoWidth: true,
  axis: "vertical",
});

const slider4 = tns({
  container: ".reviews__slider_right",
  items: 3,
  slideBy: "page",
  autoplay: true,
  nav: false,
  seed: 300,
  autoplayTimeout: 0,
  loop: true,
  controlsContainer: false,
  controls: false,
  autoplayButtonOutput: false,
  autoWidth: true,
  axis: "vertical",
});
